blacklistServiceURL: ${vcap.services.blacklist-service.credentials.uri:http://127.0.0.1:8081}/blacklist/{customerId}
records:
    ribbon:
        listOfServers: ${vcap.services.records-service.credentials.uri:http://127.0.0.1:8081}/records/{customerId}
server:
    port: ${port:8080}

